The 2nd module tasks have been solved
js-tasks-ru/js-20211109_dvpashnev pull request #2
Opened 2021-11-13 09:22 UTC by dvpashnev

The 2nd module tasks have been solved

2021-11-13 09:23 UTC, jsru commented
Добавляю преподавателя (@dosandk) для код-ревью.

2021-11-14 17:20 UTC, dosandk commented on 02-javascript-data-types/1-sort-strings/index.js
> +  const compareResult = b.normalize()
лучше отделить локали и параметры сортировки вот так:
```
a.localeCompare(b, ['ru', 'en'], { caseFirst: 'upper' }));
```

2021-11-14 17:21 UTC, dosandk commented on 02-javascript-data-types/1-sort-strings/index.js
> +  for (let i = 0; i < length - 1; i++) {
здесь нужно воспользоваться встроенным методом сортировки:
https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Global_Objects/Array/sort

2021-11-14 17:22 UTC, dosandk commented on 02-javascript-data-types/3-omit/index.js
> +  let result = {};
проверьте, а точно ли тут `let`

2021-11-14 17:22 UTC, dosandk commented on 02-javascript-data-types/2-pick/index.js
> +  let result = {};
проверьте точно ли тут `let`

2021-11-14 17:22 UTC, dosandk commented on 02-javascript-data-types/2-pick/index.js
> +    for (let [key, value] of objectEntries) {
и тут проверьте, а точно ли `key` и `value` - это `let`

2021-11-14 17:24 UTC, dosandk commented on 02-javascript-data-types/2-pick/index.js
> +  } else {
сравните данное решение с решением `omit`?
Можно ли упростить решение `pick`?

2021-11-14 17:24 UTC, dosandk requested changes
необходимо внести правки согласно комментариев

2021-11-15 09:52 UTC, jsru commented
Добавляю преподавателя (@dosandk) для код-ревью.

2021-11-15 09:53 UTC, dvpashnev commented on 02-javascript-data-types/1-sort-strings/index.js
> +  for (let i = 0; i < length - 1; i++) {
Я сначала им и хотел воспользоваться, но мне не понравилось использование callback-функции, которую я не смог приспособить под универсальное решение, и пришлось писать две дополнительных функции сравнения. Поэтому я и применил один из стандартных алгоритмов. Хотя основная функция стала лаконичнее. Есть ли способ в данном случае использовать одну callback-функцию?

2021-11-15 09:54 UTC, dvpashnev commented on 02-javascript-data-types/2-pick/index.js
> +  } else {
Естественно, можно. Но если размер Object.entries(obj) больше fields? Есть ли смысл перебирать все свойства, если нас интересуют только те, что в fields, особенно если разница в размерах будет существенная? В omit мы не можем пойти по этому пути, т.к. нам нужны свойства, которых нет в fields. А здесь можно пойти в обход. Почему не воспользоваться этим?

2021-11-15 09:58 UTC, dvpashnev commented on 02-javascript-data-types/1-sort-strings/index.js
> +  const compareResult = b.normalize()
Не нашёл такого варианта. Исправил

2021-11-15 09:58 UTC, dvpashnev commented on 02-javascript-data-types/3-omit/index.js
> +  let result = {};
Можно const. Исправил

2021-11-15 09:59 UTC, dvpashnev commented on 02-javascript-data-types/2-pick/index.js
> +  let result = {};
Можно const. Исправил

2021-11-15 09:59 UTC, dvpashnev commented on 02-javascript-data-types/2-pick/index.js
> +    for (let [key, value] of objectEntries) {
Можно const. Исправил

2021-11-16 10:01 UTC, dosandk commented on 02-javascript-data-types/1-sort-strings/index.js
> +function compareDesc(a, b) {
данная функция выглядит лишней, так как добавляет только знак `-`

2021-11-16 10:01 UTC, dosandk commented on 02-javascript-data-types/2-pick/index.js
> +  const result = {};
good 👍

2021-11-16 10:01 UTC, dosandk commented on 02-javascript-data-types/3-omit/index.js
>  export const omit = (obj, ...fields) => {
good 👍

2021-11-16 10:02 UTC, dosandk approved these changes
good 👍

2021-11-16 10:02 UTC, merged

2021-11-16 10:13 UTC, dvpashnev commented on 02-javascript-data-types/1-sort-strings/index.js
> +function compareDesc(a, b) {
Я не могу понять, как сделать без этой лишней функции